/*
 * This source file was generated by the Gradle 'init' task
 */
package cafemanager;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class UtilityTest {

    @Test
    public void doesCustomerHaveDefaultIngredients(){
        //arrange
        HashMap<String, Double> actualIngredients = Utility.createIngredientsCustomerHas();

        //assert to check size and some ingredients are inside the default ingredient
        assertEquals(9, actualIngredients.size());
        assertTrue(actualIngredients.containsKey("Milk"));
        assertTrue(actualIngredients.containsKey("Bread_Slice"));
        assertTrue(actualIngredients.containsKey("Cocoa_Powder"));
        assertFalse(actualIngredients.containsKey("Cocoa Powder"));
    }

    @Test
    public void checkingForCorrectCalculationOfPrices(){
        //int actual = Utility.calculatePrice(0, 0, 0);
        int actual2 = Utility.calculatePrice(6, 12, 3);
        int actual3 = Utility.calculatePrice(266, 532, 344);
        
        //assertEquals(0, actual);
        assertEquals(6, actual2);
        assertEquals(688, actual3);
    }

    @Test
    public void createNewIngredientIfNotInInventory() {
        HashMap<String, Double> ingredientCustomerHas = new HashMap<>();

        Utility.createAndUpdateInventoryIngredients("Milk", ingredientCustomerHas, 12.0);

        assertEquals(1, ingredientCustomerHas.size());
        assertTrue(ingredientCustomerHas.containsKey("Milk"));
        assertTrue(ingredientCustomerHas.containsValue(12.0));
    }

    @Test
    public void updateAmountIfIngredientExistsInInventory() {
        HashMap<String, Double> ingredientCustomerHas = new HashMap<>();
        ingredientCustomerHas.put("Chocolate Milk", 2.0);
        ingredientCustomerHas.put("Strawberry", 122.0);
        ingredientCustomerHas.put("Pineapple", 22.0);

        Utility.createAndUpdateInventoryIngredients("Chocolate Milk", ingredientCustomerHas, 3456.0);
        Utility.createAndUpdateInventoryIngredients("Strawberry", ingredientCustomerHas, 4.0);
        Utility.createAndUpdateInventoryIngredients("Pineapple", ingredientCustomerHas, 15.0);

        assertFalse(ingredientCustomerHas.containsValue(1234.0));
        assertTrue(ingredientCustomerHas.containsValue(3458.0));
        assertTrue(ingredientCustomerHas.containsValue(126.0));
        assertTrue(ingredientCustomerHas.containsValue(37.0));
    }

    @Test
    public void updateDishQuantityInInventoryIfDishExistsInInventory(){
        List<FoodInventory> dishInventory = new ArrayList<>();
        dishInventory.add(new FoodInventory("Hot Chocolate", 5));

        Utility.createAndUpdateInventoryDishes(dishInventory, "Hot Chocolate", 2);
        Utility.createAndUpdateInventoryDishes(dishInventory, "Hot Chocolate", 900);

        assertEquals(907, dishInventory.getFirst().getQuantity());
    }

    @Test
    public void createNewDishIfNotInInventory(){
        //created empty list
        List<FoodInventory> dishInventory = new ArrayList<>();
        
        Utility.createAndUpdateInventoryDishes(dishInventory, "Matcha", 10);

        assertEquals("Matcha", dishInventory.getFirst().getName());
        assertEquals(10, dishInventory.getFirst().getQuantity());
    }

    @Test
    public void returnUpdatedCoinsGivenYouHaveTheCorrectDishAndAmountToServeCustomer(){
        //
        List<FoodInventory> foodInventory = new ArrayList<>();
        foodInventory.add(new FoodInventory("Sandwich", 10));
        foodInventory.add(new FoodInventory("Strawberry Mocktail", 8));
        foodInventory.add(new FoodInventory("Chocolate Cheesecake", 4));

        List<Customer> customers = new ArrayList<>();
        customers.add(new Customer("Alex", "Sandwich", 3));
        customers.add(new Customer("James", "Chocolate Cheesecake", 4));
        customers.add(new Customer("Lily", "Strawberry Mocktail", 5));


        int expectedOne = Utility.serveCustomer(0, foodInventory, "Sandwich", customers , 0);
        assertEquals(6, expectedOne);

        int expectedTwo = Utility.serveCustomer(0, foodInventory, "Chocolate Cheesecake", customers , 1);
        assertEquals(8, expectedTwo);

        int expectedThree = Utility.serveCustomer(0, foodInventory,"Strawberry Mocktail", customers , 2);
        assertEquals(10 , expectedThree);
    }

    @Test
    public void returnZeroGivenFailureToServeCustomer(){
        List<FoodInventory> foodInventory = new ArrayList<>();
        foodInventory.add(new FoodInventory("Sandwich", 10));
        foodInventory.add(new FoodInventory("Strawberry Mocktail", 8));
        foodInventory.add(new FoodInventory("Chocolate Cheesecake", 4));

        List<Customer> customers = new ArrayList<>();
        customers.add(new Customer("James", "Matcha", 4));
        customers.add(new Customer("Lily", "Caramel Frappe", 34));

        //failure by not having dish in the inventory
        int expectedOne = Utility.serveCustomer(0, foodInventory, "Matcha", customers , 0);
        assertEquals(0, expectedOne);

        //failure by not having enough dishes to serve customer with
        int expectedTwo = Utility.serveCustomer(0, foodInventory, "Caramel Frappe", customers , 1);
        assertEquals(0, expectedTwo);
    }

}
